/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ApiResponse,
  RouletteBudgetUpdateRequest,
} from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const updateRouletteBudget = (
  budgetId: number,
  rouletteBudgetUpdateRequest: RouletteBudgetUpdateRequest,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<ApiResponse>(
    {
      url: `/api/admin/budgets/${budgetId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: rouletteBudgetUpdateRequest,
    },
    options
  );
};

export const getUpdateRouletteBudgetMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRouletteBudget>>,
    TError,
    { budgetId: number; data: RouletteBudgetUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRouletteBudget>>,
  TError,
  { budgetId: number; data: RouletteBudgetUpdateRequest },
  TContext
> => {
  const mutationKey = ['updateRouletteBudget'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRouletteBudget>>,
    { budgetId: number; data: RouletteBudgetUpdateRequest }
  > = props => {
    const { budgetId, data } = props ?? {};

    return updateRouletteBudget(budgetId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRouletteBudgetMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRouletteBudget>>
>;
export type UpdateRouletteBudgetMutationBody = RouletteBudgetUpdateRequest;
export type UpdateRouletteBudgetMutationError = unknown;

export const useUpdateRouletteBudget = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRouletteBudget>>,
      TError,
      { budgetId: number; data: RouletteBudgetUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateRouletteBudget>>,
  TError,
  { budgetId: number; data: RouletteBudgetUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateRouletteBudgetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
