/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ApiResponse,
  RouletteBudgetCreateRequest,
} from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const createRouletteBudget = (
  rouletteBudgetCreateRequest: RouletteBudgetCreateRequest,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponse>(
    {
      url: `/api/admin/budgets`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: rouletteBudgetCreateRequest,
      signal,
    },
    options
  );
};

export const getCreateRouletteBudgetMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRouletteBudget>>,
    TError,
    { data: RouletteBudgetCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRouletteBudget>>,
  TError,
  { data: RouletteBudgetCreateRequest },
  TContext
> => {
  const mutationKey = ['createRouletteBudget'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRouletteBudget>>,
    { data: RouletteBudgetCreateRequest }
  > = props => {
    const { data } = props ?? {};

    return createRouletteBudget(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRouletteBudgetMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRouletteBudget>>
>;
export type CreateRouletteBudgetMutationBody = RouletteBudgetCreateRequest;
export type CreateRouletteBudgetMutationError = unknown;

export const useCreateRouletteBudget = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRouletteBudget>>,
      TError,
      { data: RouletteBudgetCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createRouletteBudget>>,
  TError,
  { data: RouletteBudgetCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateRouletteBudgetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
