/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { ApiResponseRouletteParticipateResponse } from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const participate = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseRouletteParticipateResponse>(
    { url: `/api/roulettes/current/participants`, method: 'POST', signal },
    options
  );
};

export const getParticipateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof participate>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof participate>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['participate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof participate>>,
    void
  > = () => {
    return participate(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ParticipateMutationResult = NonNullable<
  Awaited<ReturnType<typeof participate>>
>;

export type ParticipateMutationError = unknown;

export const useParticipate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof participate>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof participate>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getParticipateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
