/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseRouletteParticipationHistoryListQueryResponse,
  GetParticipationHistoriesParams,
} from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getParticipationHistories = (
  params?: GetParticipationHistoriesParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseRouletteParticipationHistoryListQueryResponse>(
    {
      url: `/api/admin/roulettes/participations`,
      method: 'GET',
      params,
      signal,
    },
    options
  );
};

export const getGetParticipationHistoriesQueryKey = (
  params?: GetParticipationHistoriesParams
) => {
  return [
    `/api/admin/roulettes/participations`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetParticipationHistoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getParticipationHistories>>,
  TError = unknown,
>(
  params?: GetParticipationHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getParticipationHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetParticipationHistoriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getParticipationHistories>>
  > = ({ signal }) => getParticipationHistories(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getParticipationHistories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetParticipationHistoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getParticipationHistories>>
>;
export type GetParticipationHistoriesQueryError = unknown;

export function useGetParticipationHistories<
  TData = Awaited<ReturnType<typeof getParticipationHistories>>,
  TError = unknown,
>(
  params: undefined | GetParticipationHistoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getParticipationHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getParticipationHistories>>,
          TError,
          Awaited<ReturnType<typeof getParticipationHistories>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetParticipationHistories<
  TData = Awaited<ReturnType<typeof getParticipationHistories>>,
  TError = unknown,
>(
  params?: GetParticipationHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getParticipationHistories>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getParticipationHistories>>,
          TError,
          Awaited<ReturnType<typeof getParticipationHistories>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetParticipationHistories<
  TData = Awaited<ReturnType<typeof getParticipationHistories>>,
  TError = unknown,
>(
  params?: GetParticipationHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getParticipationHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetParticipationHistories<
  TData = Awaited<ReturnType<typeof getParticipationHistories>>,
  TError = unknown,
>(
  params?: GetParticipationHistoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getParticipationHistories>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetParticipationHistoriesQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
