/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ApiResponseOrderHistoryListQueryResponse } from '.././models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getOrderHistory = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseOrderHistoryListQueryResponse>(
    {
      url: `/api/orders/history`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getOrderHistoryQueryKey = () => {
  return ['getOrderHistory'];
};

export const getOrderHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrderHistory>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOrderHistory>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const queryKey = getOrderHistoryQueryKey();

  const { query: queryOptions, request: requestOptions } = options
    ? options.query &&
      'queryKey' in options.query &&
      options.query.queryKey
      ? options
      : { ...options, query: { ...options.query, queryKey } }
    : { query: { queryKey }, request: undefined };

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderHistory>>> = ({
    signal,
  }) => getOrderHistory(requestOptions, signal);

  return { queryFn, ...queryOptions };
};

export type GetOrderHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrderHistory>>
>;
export type GetOrderHistoryQueryError = unknown;

export const useGetOrderHistory = <
  TData = Awaited<ReturnType<typeof getOrderHistory>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOrderHistory>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseQueryResult<TData, TError> => {
  const queryOptions = getOrderHistoryQueryOptions(options);

  return useQuery(queryOptions);
};