/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { ApiResponse } from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const cancelOrder = (
  orderId: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponse>(
    { url: `/api/admin/orders/${orderId}/cancel`, method: 'POST', signal },
    options
  );
};

export const getCancelOrderMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelOrder>>,
    TError,
    { orderId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelOrder>>,
  TError,
  { orderId: number },
  TContext
> => {
  const mutationKey = ['cancelOrder'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelOrder>>,
    { orderId: number }
  > = props => {
    const { orderId } = props ?? {};

    return cancelOrder(orderId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelOrder>>
>;

export type CancelOrderMutationError = unknown;

export const useCancelOrder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelOrder>>,
      TError,
      { orderId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof cancelOrder>>,
  TError,
  { orderId: number },
  TContext
> => {
  const mutationOptions = getCancelOrderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
