/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ApiResponseOrderListQueryWithUserResponse,
  GetOrderListParams,
} from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getOrderList = (
  params?: GetOrderListParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseOrderListQueryWithUserResponse>(
    { url: `/api/admin/orders`, method: 'GET', params, signal },
    options
  );
};

export const getGetOrderListQueryKey = (params?: GetOrderListParams) => {
  return [`/api/admin/orders`, ...(params ? [params] : [])] as const;
};

export const getGetOrderListQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrderList>>,
  TError = unknown,
>(
  params?: GetOrderListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrderList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOrderListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderList>>> = ({
    signal,
  }) => getOrderList(params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 300000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrderList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrderListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrderList>>
>;
export type GetOrderListQueryError = unknown;

export function useGetOrderList<
  TData = Awaited<ReturnType<typeof getOrderList>>,
  TError = unknown,
>(
  params: undefined | GetOrderListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrderList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderList>>,
          TError,
          Awaited<ReturnType<typeof getOrderList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrderList<
  TData = Awaited<ReturnType<typeof getOrderList>>,
  TError = unknown,
>(
  params?: GetOrderListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrderList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrderList>>,
          TError,
          Awaited<ReturnType<typeof getOrderList>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrderList<
  TData = Awaited<ReturnType<typeof getOrderList>>,
  TError = unknown,
>(
  params?: GetOrderListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrderList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetOrderList<
  TData = Awaited<ReturnType<typeof getOrderList>>,
  TError = unknown,
>(
  params?: GetOrderListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOrderList>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrderListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
