/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 로그인 요청 데이터
 */
export interface LoginRequest {
  /** 사용자 닉네임 */
  nickname: string;
}
