/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 룰렛 상태 조회 응답
 */
export interface RouletteStatusQueryResponse {
  /** 오늘 참여 여부 */
  hasParticipatedToday: boolean;
  /** 남은 예산 */
  remainingBudget: number;
}
