/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */

export interface SimpleUser {
  id: number;
  nickname: string;
  userBalance: number;
}
