/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { ApiResponse } from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const cancelRouletteParticipation = (
  rouletteHistoryId: number,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseUnit>(
    {
      url: `/api/admin/roulettes/${rouletteHistoryId}/cancel`,
      method: 'POST',
      signal,
    },
    options
  );
};

export const getCancelRouletteParticipationMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelRouletteParticipation>>,
    TError,
    { rouletteHistoryId: number },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelRouletteParticipation>>,
  TError,
  { rouletteHistoryId: number },
  TContext
> => {
  const mutationKey = ['cancelRouletteParticipation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelRouletteParticipation>>,
    { rouletteHistoryId: number }
  > = props => {
    const { rouletteHistoryId } = props ?? {};

    return cancelRouletteParticipation(rouletteHistoryId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelRouletteParticipationMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelRouletteParticipation>>
>;

export type CancelRouletteParticipationMutationError = unknown;

export const useCancelRouletteParticipation = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelRouletteParticipation>>,
      TError,
      { rouletteHistoryId: number },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof cancelRouletteParticipation>>,
  TError,
  { rouletteHistoryId: number },
  TContext
> => {
  const mutationOptions =
    getCancelRouletteParticipationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
