/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ApiResponseUnit,
  ProductUpdateRequest,
} from '@shared/api-models';

import { axiosInstance } from '.././axiosInstance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const updateProduct = (
  id: number,
  productUpdateRequest: ProductUpdateRequest,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<ApiResponseUnit>(
    {
      url: `/api/admin/products/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: productUpdateRequest,
    },
    options
  );
};

export const getUpdateProductMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProduct>>,
    TError,
    { id: number; data: ProductUpdateRequest },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: number; data: ProductUpdateRequest },
  TContext
> => {
  const mutationKey = ['updateProduct'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProduct>>,
    { id: number; data: ProductUpdateRequest }
  > = props => {
    const { id, data } = props ?? {};

    return updateProduct(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProduct>>
>;
export type UpdateProductMutationBody = ProductUpdateRequest;
export type UpdateProductMutationError = unknown;

export const useUpdateProduct = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProduct>>,
      TError,
      { id: number; data: ProductUpdateRequest },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateProduct>>,
  TError,
  { id: number; data: ProductUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateProductMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
