/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { OrderHistoryListQueryResponse } from './orderHistoryListQueryResponse';

export interface ApiResponseOrderHistoryListQueryResponse {
  code: string;
  message?: string;
  data?: OrderHistoryListQueryResponse;
}
