/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { OrderHistoryItemResponseStatus } from './orderHistoryItemResponseStatus';

export interface OrderHistoryItemResponse {
  id: number;
  productName: string;
  deductedPoints: number;
  status: OrderHistoryItemResponseStatus;
  createdAt: string;
}
