/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 룰렛 참여 응답
 */
export interface RouletteParticipateResponse {
  /** 획득한 포인트 */
  value?: number;
}
