/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Roulette API
 * 룰렛 게임 API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 룰렛 참여 응답
 */
export interface RouletteParticipateResponse {
  /** 획득한 포인트 */
  value?: number;
}
